---
# configure_microsoft_repos/tasks/dnf.yml

# This file should work for any role where you need to add the Microsoft Linux repository information.
# When additional information is required (e.g. repo information for vscode) it will be handled by that role.

# First obtain, verify, and install the information.
# https://github.com/microsoft/linux-package-repositories#signature-verification

# https://learn.microsoft.com/en-us/linux/packages#how-to-install-microsoft-software-packages-using-the-linux-repository
# https://packages.microsoft.com/keys/microsoft.asc
# Public Key ID: Microsoft (Release signing) gpgsecurity@microsoft.com
# Public Key Fingerprint: BC52 8686 B50D 79E3 39D3 721C EB3E 94AD BE12 29CF
# https://packages.microsoft.com/config/
# https://packages.microsoft.com/config/fedora/40/
- name: Obtain Microsoft Signing Key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc
    mode: '0644'

# Verify and import the signing key based on the known fingerprint
# https://learn.microsoft.com/en-us/linux/packages#how-to-use-the-gpg-repository-signing-key
- name: Verify and import Microsoft's signing key
  ansible.builtin.rpm_key:
    state: present
    key: /tmp/microsoft.asc
    fingerprint: BC52 8686 B50D 79E3 39D3 721C EB3E 94AD BE12 29CF
  become: yes
  become_method: sudo

- name: Obtain the RPM repo config package
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/config/{{ ansible_facts["distribution"] | lower }}/{{ ansible_facts["distribution_version"] }}/packages-microsoft-prod.rpm
    dest: /tmp/packages-microsoft-prod.rpm
    mode: '0644'

# This uses the public key to verify the binary RPM package integrity before we install it as root
- name: Verify the RPM repo config package
  ansible.builtin.shell: |
    rpm --checksig /tmp/packages-microsoft-prod.rpm
  args:
    executable: /bin/bash

# If the signature check passes, install it
- name: Install the RPM repo config package
  ansible.builtin.dnf:
    name: /tmp/packages-microsoft-prod.rpm
    state: present
  become: yes
  become_method: sudo

- name: Update dnf cache
  ansible.builtin.dnf:
    update_cache: yes
  become: yes
  become_method: sudo

# TO DO: Set priority for either the Microsoft package feed, or Fedora's archive