---
# handlers file for install_unbound

# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html
- name: Restart Unbound
  ansible.builtin.service:
    name: unbound
    state: restarted
  become: true
  become_method: ansible.builtin.sudo
