---
# configure_gnupg/tasks/dnf.yml

# NOTE: On Fedora, scdaemon is included with the gnupg2 package

- name: Install smartcard packages (RedHat / Fedora)
  ansible.builtin.dnf:
    pkg:
      - pcsc-lite
    state: latest
  become: yes
  become_method: sudo