---
# install_ykman/tasks/apt.yml

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#examples
- name: Install Dependancies (apt)
  ansible.builtin.apt:
    pkg:
      - pcscd
      - scdaemon
      - swig
      - libpcsclite-dev
    state: latest
    update_cache: true
  become: true
  become_method: ansible.builtin.sudo

- name: Install pipx (apt)
  ansible.builtin.apt:
    pkg:
      - pipx
    state: latest
    update_cache: true
  when: ansible_facts['distribution_major_version'] >= "24"
  become: true
  become_method: ansible.builtin.sudo

- name: Install python3-pip (apt)
  ansible.builtin.apt:
    pkg:
      - python3-pip
    state: latest
    update_cache: true
  when: ansible_facts['distribution_major_version'] < "24"
  become: true
  become_method: ansible.builtin.sudo
