---
# install_chrome/tasks/install-chrome.yml

# Instructions: https://www.google.com/linuxrepositories/

# Replaces https://dl.google.com/linux/linux_signing_key.pub with a keyserver URL to Chrome's latest public key without the obsolete DSA signature
#   "NOTE: From early 2023 onward, all Linux RPM packages are signed with periodically rotated subkeys of the 0xD38B4796 signing key.
#          The 0x7FAC5991 signing key is obsoleted by this change."
- name: Obtain Google Chrome Signing Key
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xeb4c1bfd4f042f6dddccec917721f63bd38b4796
    dest: /tmp/google-chrome.asc
    mode: "0600"

# This task will stop the playbook here if the key does not match the known fingerprint
# This is the same key as https://dl.google.com/linux/linux_signing_key.pub, but without the obsolete DSA signature
- name: Verify Google Chrome Key Fingerprint
  ansible.builtin.shell: |
    set -o pipefail
    gpg /tmp/google-chrome.asc | grep -P "EB4C\s?1BFD\s?4F04\s?2F6D\s?DDCC\s?\s?EC91\s?7721\s?F63B\s?D38B\s?4796"
  args:
    executable: /bin/bash

# Another note from the Google install instructions:
#   "NOTE: On systems with older versions of apt (i.e. versions prior to 1.4), the ASCII-armored format public
#          key must be converted to binary format before it can be used by apt."
# This includes OS's earlier than Ubuntu 18.04 and Debian 10, which aren't supported right now by this role

# Install the key (Debian / Ubuntu)
- name: Copy Google Chrome Signing Key Into Trusted Keys Folder (Debian / Ubuntu)
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/google-chrome.asc
    dest: /etc/apt/trusted.gpg.d/
    owner: root
    group: root
    mode: "0644"
  when: ansible_facts['os_family'] == "Debian"
  become: true
  become_method: ansible.builtin.sudo

# This will add the Chrome Linux repo information and automatically update apt's package cache for installation
- name: Add Google Chrome Repository (Debian / Ubuntu)
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    update_cache: true
    state: present
    mode: "0644"
  when: ansible_facts['os_family'] == "Debian"
  become: true
  become_method: ansible.builtin.sudo

# Import the signing key with RPM
- name: Import the Google Chrome Signing Key (RedHat / Fedora)
  ansible.builtin.rpm_key:
    state: present
    key: /tmp/google-chrome.asc
  when: ansible_facts['os_family'] == "RedHat"
  become: true
  become_method: ansible.builtin.sudo

# Use package module to work on any distro
- name: Install Google Chrome
  ansible.builtin.package:
    name:
      - google-chrome-stable
    state: present
  become: true
  become_method: ansible.builtin.sudo

- name: Create Chrome Managed Policy Folders
  ansible.builtin.file:
    path: /etc/opt/chrome/policies/managed
    state: directory
    mode: "0755"
  become: true
  become_method: ansible.builtin.sudo

- name: Create Chrome Recommended Policy Folders
  ansible.builtin.file:
    path: /etc/opt/chrome/policies/recommended
    state: directory
    mode: "0755"
  become: true
  become_method: ansible.builtin.sudo

# policies.json must be under files/policies.json
- name: Install Google Chrome Policy File
  ansible.builtin.copy:
    src: policies.json
    dest: /etc/opt/chrome/policies/managed/
    owner: root
    group: root
    mode: "0644"
  become: true
  become_method: ansible.builtin.sudo
