---
# build_ubuntu_desktop/tasks/network.yml

# If you're building an Ubuntu desktop environment on top of a server image,
# you'll need to change networking to be handled by NetworkManager.
# See: https://github.com/canonical/autoinstall-desktop/blob/4fafe4935501a70e59a54f5138ced14512c5684f/autoinstall.yaml#L57

- name: Remove existing netplan files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/netplan/00-installer-config*.yaml"
  become: true
  become_method: ansible.builtin.sudo

- name: Create new netplan files for NetworkManager
  ansible.builtin.copy:
    dest: /etc/netplan/01-network-manager-all.yaml
    owner: root
    group: root
    mode: '0640'
    content: |
      network:
        version: 2
        renderer: NetworkManager
  become: true
  become_method: ansible.builtin.sudo

- name: Disable systemd-networkd on next boot
  ansible.builtin.service:
    name: systemd-networkd
    enabled: false
  become: true
  become_method: ansible.builtin.sudo

- name: Disable systemd-networkd-wait-online on next boot
  ansible.builtin.service:
    name: systemd-networkd-wait-online
    enabled: false
  become: true
  become_method: ansible.builtin.sudo

- name: Enable UFW (Firewall)
  ansible.builtin.shell: |
    set -o pipefail
    echo y | ufw enable
  args:
    executable: /bin/bash
  become: true
  become_method: ansible.builtin.sudo

- name: Allow SSH (Firewall)
  ansible.builtin.command: ufw allow ssh
  become: true
  become_method: ansible.builtin.sudo
