---
# build_ubuntu_desktop/tasks/ssh.yml

- name: Enforce Public Key Auth (sshd_config)
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^.PasswordAuthentication.*$'
    line: PasswordAuthentication no
  notify: Restart SSH
  become: true
  become_method: ansible.builtin.sudo
