---
# configure_ssh/tasks/compliance.yml

- name: "Install hardened config files (ssh_config, sshd_config)"
  ansible.builtin.copy:
    remote_src: false
    src: "{{ item }}"
    dest: "/etc/ssh/"
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: true
  loop:
    - "sshd_config"
    - "ssh_config"
  notify: Restart SSH
  become: true
  become_method: ansible.builtin.sudo

- name: "Install custom login banner"
  ansible.builtin.copy:
    remote_src: false
    src: issue
    dest: "/etc/{{ item }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: true
  loop:
    - issue
    - issue.net
  become: true
  become_method: ansible.builtin.sudo

- name: "Verify root is the group and owner of server ssh path"
  ansible.builtin.file:
    path: /etc/ssh
    owner: root
    group: root
    recurse: true
  become: true
  become_method: ansible.builtin.sudo

- name: "Verify permissions on server config file"
  ansible.builtin.file:
    path: /etc/ssh/sshd_config
    mode: "0600"
  become: true
  become_method: ansible.builtin.sudo

- name: "Verify permissions on server private keys"
  ansible.builtin.shell: |
    set -o pipefail
    chmod 0600 /etc/ssh/*_key
  args:
    executable: /bin/bash
  become: true
  become_method: ansible.builtin.sudo

- name: "Verify permissions on server public keys"
  ansible.builtin.shell: |
    set -o pipefail
    chmod 0644 /etc/ssh/*.pub
  args:
    executable: /bin/bash
  become: true
  become_method: ansible.builtin.sudo
