---
# install_vscode/tasks/snap.yml

# https://code.visualstudio.com/docs/setup/linux

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

# This task only executes if prefer_snap == true in vars/main.yml
# This also checks to make sure snap is actually installed (it is by default)
- name: Install VSCode (snap)
  ansible.builtin.shell: |
    snap install --classic code # or code-insiders
  args:
    executable: /bin/bash
  when: ("'snap' in ansible_facts.packages") and
        (ansible_facts['distribution'] == "Ubuntu")
  become: yes
  become_method: sudo