---
# install_powershell/tasks/install-powershell.yml

# https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.4

# Install PowerShell
- name: Install PowerShell
  ansible.builtin.package:
    pkg:
      - powershell
    state: latest
  become: true
  become_method: ansible.builtin.sudo

# https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.4#create-persistent-environment-variables-on-non-windows-platforms
- name: Write PowerShell Telemetry Profile Script
  ansible.builtin.blockinfile:
    state: present
    create: true
    path: /etc/profile.d/powershell.sh
    mode: '0644'
    owner: root
    group: root
    block: |
      #!/bin/bash
      # Disable PowerShell telemetry system-wide
      export POWERSHELL_TELEMETRY_OPTOUT=1
  become: true
  become_method: ansible.builtin.sudo

- name: Include /etc/profile.d/powershell.sh in /etc/bash.bashrc
  ansible.builtin.blockinfile:
    state: present
    create: true
    insertbefore: '^umask\s\d+$'
    prepend_newline: true
    append_newline: true
    path: /etc/bash.bashrc
    mode: '0644'
    owner: root
    group: root
    block: |
      if [ -f /etc/profile.d/powershell.sh ]; then
          . /etc/profile.d/powershell.sh
      fi
  become: true
  become_method: ansible.builtin.sudo
