---
# tasks file for configure_gnupg

- name: Include configuration tasks
  include_tasks: config.yml

- name: Include apt tasks
  include_tasks: apt.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Include dnf tasks
  include_tasks: dnf.yml
  when: ansible_facts['os_family'] == "RedHat"
