---
# tasks file for install_unbound

# Installs unbound, applies the correct service and configuration changes for both
# Debian and RedHat based systems.
- name: Install Unbound
  include_tasks: install-unbound.yml
