---
# build_kali_desktop/tasks/guest-utils.yml

# Ensures the spice agent is installed when virtualized by virt-manager / libvirt
- name: Install spice-vdagent
  ansible.builtin.apt:
    pkg:
      - spice-vdagent
    state: present
    update_cache: true
  become: true
  become_method: ansible.builtin.sudo
  when: ansible_system_vendor == "QEMU"
