---
# build_ubuntu_desktop/tasks/files.yml

# Copies all of the utilities under this role's files/* path to /usr/local/bin/ on the target node
- name: Install utility scripts
  ansible.builtin.copy:
    remote_src: false
    src: "{{ item }}"
    dest: /usr/local/bin
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_fileglob:
    - "*.sh"
  become: true
  become_method: ansible.builtin.sudo

# Installs a hardened Firefox policy
- name: Create Firefox policy folder
  ansible.builtin.file:
    state: directory
    mode: '0755'
    owner: root
    group: root
    path: /etc/firefox/policies
  become: true
  become_method: ansible.builtin.sudo

- name: Install Firefox policies.json
  ansible.builtin.copy:
    remote_src: false
    src: firefox-policies.json
    dest: /etc/firefox/policies/policies.json
    mode: '0644'
    owner: root
    group: root
  become: true
  become_method: ansible.builtin.sudo

# Install udev rules for Yubikeys
# https://developers.yubico.com/yubikey-manager/Device_Permissions.html
# https://github.com/Yubico/yubikey-personalization/blob/master/69-yubikey.rules
# https://github.com/Yubico/libu2f-host/blob/master/70-u2f.rules
- name: Install udev rules for Yubikeys
  ansible.builtin.copy:
    remote_src: false
    src: "{{ item }}"
    dest: /etc/udev/rules.d/
    owner: 'root'
    group: 'root'
    mode: '0755'
  loop:
    - "69-yubikey.rules"
    - "70-u2f.rules"
  become: true
  become_method: ansible.builtin.sudo

- name: Reload udevadm control
  ansible.builtin.shell: |
    udevadm control --reload
  become: true
  become_method: ansible.builtin.sudo
