---
# install_vscode/tasks/config.yml

- name: Creating path for VSCode settings file
  ansible.builtin.file:
    path: "/home/{{ ansible_facts['env']['USER'] }}/.config/Code/User"
    state: directory
    mode: '0755'

- name: Install settings.json for VSCode
  ansible.builtin.copy:
    remote_src: no
    src: "{{ item }}"
    dest: "/home/{{ ansible_facts['env']['USER'] }}/.config/Code/User/settings.json"
    owner: "{{ ansible_facts['env']['USER'] }}"
    group: "{{ ansible_facts['env']['USER'] }}"
    mode: '0644'
  with_fileglob:
    - "settings.json"