---
# defaults file for install_auditd

install_ruleset: "local"                 # local|stig|pci|ospp
install_ruleset_plus_base: "enabled"     # enabled|disabled, installs the 10-base-config.rules and 99-finalize.rules, set to "disabled" if your local file contains these
default_rules_path: /etc/audit/rules.d/  # Change this if yours is different
log_format: "ENRICHED"                   # ENRICHED or RAW, use ENRICHED if reviewing logs on another system
max_log_file: "8"                        # 8MB total file size per log file, a good default
num_logs: "10"                           # 10 total log files, default for an endpoint shipping logs to a SIEM, use 50+ for a log server

# Laurel options
# https://github.com/threathunters-io/laurel/blob/master/INSTALL.md
install_laurel: "false"      # Set to true to install laurel
laurel_binary_type: "glibc"  # musl|glibc Choose between the statically linked musl version, or the dynamically linked glibc version