# .github/workflows/packer.yml

# Taken from:
# https://github.com/hashicorp/setup-packer

name: packer

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: |
          for path in ubuntu-* kali-* debian-*
          do
            cd "$path"
            packer init .
            cd -
          done

      - name: Run `packer fmt`
        id: fmt
        run: |
          for path in ubuntu-* kali-* debian-*
          do
            cd "$path"
            packer fmt .
            cd -
          done

      - name: Run `packer validate`
        id: validate
        run: |
          for path in ubuntu-* kali-* debian-*
          do
            cd "$path"
            packer validate .
            cd -
          done