# .github/workflows/packer.yml

# Taken from:
# https://github.com/hashicorp/setup-packer

name: packer

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PRODUCT_VERSION: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: |
          for path in kali-linux debian ubuntu/ubuntu-cloudinit ubuntu/ubuntu-preseed
          do
            cd "$path"
            packer init .
            cd -
          done

      # The -recursive option will cover the entire repo
      - name: Run `packer fmt`
        id: fmt
        run: |
          packer fmt -recursive .

      # Includes a fix to handle .pkrvars.hcl files
      - name: Run `packer validate`
        id: validate
        run: |
          for path in ubuntu/ubuntu-cloudinit ubuntu/ubuntu-preseed kali-linux debian
          do
            cd "$path"
            for file in ./*.pkrvars.hcl
            do
              packer validate -var-file "$file" .
            done
            cd -
          done
