---
# handlers file for configure_ssh

# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html
- name: Restart SSH
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: true
  become_method: ansible.builtin.sudo
